title: 个人主页测试
author: OXlouis
email: 123123123@qq.com
description: > # this means to ignore newlines until "baseurl:"
  something interesting.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
